server:
  port: 9090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://172.29.7.168:35432/qysca
    username: qysca
    password: qysca
    show-sql: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use-jdbc-metadata-defaults: false
  redis:
    host: 172.29.7.168
    port: 37379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间 负值表示没有限制
        max-wait: -1ms

uploadFolder: src/main/resources/static/upload/
tempPomFolder: src/main/resources/static/temp/
tempGoFolder: src/main/resources/static/temp/go/
tempPythonFolder: src/main/resources/static/temp/python
# maxFileSize 单个数据大小
spring.servlet.multipart.maxFileSize: 10MB
# maxRequestSize 是总数据大小
spring.servlet.multipart.maxRequestSize: 500MB