#server:
#  port: 9090
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/qysca?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true

#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: com.sentistrength.model.po
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt:
#  secret: 6e12d69c-af21-4cc2-b32d-3fa949b50106
#  expire: 86400000