server:
  port: 9090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://172.29.7.168:37018/sca
    neo4j:
      uri: bolt://172.29.7.168:37687
      username: neo4j
      password: 2020tyhj